[package]
name = "solana-wallet-adapter"
version = "0.1.0"
authors = ["448-OG <superuser@448.africa>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Solana Wallet Adapter for Rust clients written in pure Rust"
homepage = "https://github.com/JamiiDao"
repository = "https://github.com/JamiiDao/SolanaWalletAdapter"
readme = "./README.md"


[lib]
name = "solana_wallet_adapter"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
console_log = "1.0.0"
log = "0.4.14"
console_error_panic_hook = "0.1.6"
bs58 = { version = "0.5.1", default-features = false }
ed25519-dalek = { version = "2.1.1", default-features = false, features = [
    "signature",
] }
web-sys = { version = "0.3.70", features = ["Window", "Document"] }
js-sys = "0.3.70"
wasm-bindgen-futures = "0.4.43"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
